import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/home.module.css";
import Lhswrapper from "@/components/home/main_lhs/lhswrapper";
import Rhswrapper from "@/components/home/main_rhs/rhswrapper";
import Popup from "@/components/home/reusable/popup";
import Rnewchat from "@/components/newchat/newchatwidget";
import Alert from "@/components/home/reusable/alert";
import { Rhsprovider } from "@/context/provider";
import { Lhsprovider } from "@/context/lhsprovider";
import { Gcommonprovider } from "@/context/common_global";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
        </style>
      </Head>

      {/* Main home page template which can include  */}
      <Gcommonprovider>
        <div className={styles.app_container}>
          {/* LHS SECTION */}
          <div id={styles.left_section}>
            {/* SECTION 1. HEADER 2. CONTENT 3.FOOTER */}
            <Lhsprovider>
            <Lhswrapper />
            </Lhsprovider>
          </div>

          {/* RHS SECTION */}
          <main className={styles.main_rhs_container}>
            <Rhsprovider>
              <Rhswrapper />
            </Rhsprovider>
          </main>
        </div>
      </Gcommonprovider>

      <div className="overlay" g-overlay id="overlay"></div>
      {/* <Alert msg="Hello this is testing" /> */}
    </>
  );
}
