// import Head from "next/head";
// import { Inter } from "next/font/google";
// import styles from "../styles/home.module.css";
// import Lhswrapper from "@/components/home/main_lhs/lhswrapper";
// import { Rhsprovider } from "@/context/provider";
// import { Lhsprovider } from "@/context/lhsprovider";
// import { Gcommonprovider } from "@/context/common_global";
// import Landingrhs from "@/components/landing/landingrhs";

// const inter = Inter({ subsets: ["latin"] });

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//         <style>
//           @import
//           url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
//         </style>
//       </Head>

//       {/* Main home page template which can include  */}
//       <Gcommonprovider>
//         <div className={styles.app_container}>
//           {/* LHS SECTION */}
//           <div id={styles.left_section}>
//             {/* SECTION 1. HEADER 2. CONTENT 3.FOOTER */}
//             <Lhsprovider>
//               <Lhswrapper />
//             </Lhsprovider>
//           </div>

//           {/* RHS SECTION */}
//           <main className={styles.main_rhs_container}>
//             <Rhsprovider>
//               <Landingrhs />
//             </Rhsprovider>
//           </main>
//         </div>
//       </Gcommonprovider>

//       <div className="overlay" g-overlay id="overlay"></div>
//       {/* <Alert msg="Hello this is testing" /> */}
//     </>
//   );
// }
